spring.application.name=KafkaPractice
spring.kafka.bootstrap-servers=localhost:9092
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/mydatabase
spring.data.mongodb.database=mydatabase